### ISSUE TITLE
[Testing] Project config not syncing plugin (Commerce) data

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#1953]
### Description

I was trying to access product types from Commerce in my unit tests, but it seems like the project config is not syncing data for plugins. I wasn't sure if the expectation was that we'd need to add fixtures for product types or if the config data should be syncing over.

### Steps to reproduce

1. Add Commerce Plugin
2. Add a product type
3. Add Commerce plugin to `codeception.yml`
4. See that DB syncs other project config data, creates the commerce tables, but doesn't sync the product type

```yml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
bootstrap: _bootstrap.php
modules:
  config:
    \craft\test\Craft:
      configFile: "tests/_craft/config/test.php"
      entryUrl: "http://client.test/index.php"
      projectConfig: { folder: 'config/project', reset: false }
      migrations: []
      plugins: [
        {
          class: '\craft\commerce\Plugin',
          handle: 'commerce'
        }
      ]
      cleanup: true
      transaction: true
      dbSetup: { clean: true, setupCraft: true }
```

Product types exist in project config:
![image](https://user-images.githubusercontent.com/199985/104247207-4d312b80-5435-11eb-87d9-50c431a3fdfc.png)

### Additional info

- Craft version: Craft Pro 3.5.16
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>3.2.12</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.8.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Scout</th>
                        <td>2.3.1</td>
                    </tr>
                            </tbody>
        </table>

Let me know if there is any additional info I can provide or if this is expected behavior, and I'd need to create fixtures for this data.
