### ISSUE TITLE
Setting an email's language seems to fail because of a bad schemaVersion comparison

### ISSUE THREAD

**Issue by jaspertandy** [craftcms/commerce#2574]
### Description

project.yaml:

```
plugins:
  commerce:
    edition: pro
    enabled: true
    licenseKey: [REDACTED]
    settings:
      _orderPdfPath: null
      activeCartDuration: 3600
      allowCheckoutWithoutPayment: false
      allowEmptyCartOnCheckout: false
      allowPartialPaymentOnCheckout: false
      autoSetNewCartAddresses: true
      cartVariable: cart
      defaultView: commerce/orders
      dimensionUnits: cm
      emailSenderAddress: russell@builtbybuffalo.com
      emailSenderAddressPlaceholder: null
      emailSenderName: russell@builtbybuffalo.com
      emailSenderNamePlaceholder: null
      freeOrderPaymentStrategy: complete
      gatewayPostRedirectTemplate: ''
      loadCartRedirectUrl: null
      minimumTotalPriceStrategy: default
      orderReferenceFormat: '{{number[:7]}}'
      paymentCurrency: null
      pdfAllowRemoteImages: false
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      purgeInactiveCarts: true
      purgeInactiveCartsDuration: 7776000
      requireBillingAddressAtCheckout: false
      requireShippingAddressAtCheckout: false
      requireShippingMethodSelectionAtCheckout: false
      showCustomerInfoTab: true
      updateBillingDetailsUrl: ''
      updateCartSearchIndexes: true
      useBillingAddressForTax: false
      validateBusinessTaxIdAsVatId: false
      validateCartCustomFieldsOnSubmission: false
      weightUnits: kg
```

Orders are failing because language is missing, and it is null in the database, but it is present in my YAML:

```
bcc: null
cc: null
enabled: true
language: en
name: 'New voucher order'
plainTextTemplatePath: ''
recipientType: customer
replyTo: [REDACTED]
subject: 'Your order'
templatePath: _email/index
to: null
```

I have traced this to [this code](https://github.com/craftcms/commerce/blob/develop/src/services/Emails.php#L341) which is checking for a schemaVersion greater than 3.2.13 before setting language, but my schemaVersion is null as you can see from my project.yaml file above.

I don't really have sufficient experience to supply a fix here, as I don't know whether I should have a schema version that is somehow missing, or whether this comparison should also be checking for null as well?

There is a comment in this file:

```
            // todo: remove schema version condition after next beakpoint
```

So I'm not sure if you dropped the notion of schema versioning and I'm somehow caught in the middle of something here?

### Steps to reproduce

Afraid I didn't set up this project so I don't know how we got here, but I'm happy to give specific information where I can.

### Additional info

- Craft CMS version: 3.6.15
- Craft Commerce version: 3.3.5.1
- PHP version: 7.4.24
